# Generated by Django 5.2.7 on 2026-09-12 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Configuracao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auto_print_on_kitchen_arrival', models.BooleanField(default=False, help_text='Quando ativado, todo pedido com ao menos uma linha de preparo de cozinha é enviado automaticamente para a impressora térmica assim que é registrado. Pedidos apenas de balcão (sem linha de preparo) nunca disparam a impressão automática.', verbose_name='Imprimir pedido automaticamente ao chegar na cozinha')),
            ],
            options={
                'verbose_name': 'Configuração',
                'verbose_name_plural': 'Configuração',
            },
        ),
    ]
