# Generated by Django 5.2.7 on 2026-09-12 08:12

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracao',
            name='alert_sound',
            field=models.FileField(blank=True, help_text='Som tocado no servidor quando a impressão automática falha. Em branco usa o som padrão embutido no projeto.', null=True, upload_to=core.models._alert_sound_upload_to, verbose_name='som do alerta de falha de impressão'),
        ),
    ]
