# Generated by Django 5.2.7 on 2026-09-11 05:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tables', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nome da comanda (cliente, grupo ou como o salão a chama).', max_length=100, verbose_name='nome')),
                ('status', models.CharField(choices=[('open', 'Aberta'), ('closed', 'Fechada')], default='open', help_text='Comandas novas começam em "aberta"; fechá-la a aposenta.', max_length=10, verbose_name='status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criada em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizada em')),
                ('closed_at', models.DateTimeField(blank=True, help_text='Momento em que a comanda foi fechada; vazio enquanto estiver aberta.', null=True, verbose_name='fechada em')),
                ('table', models.ForeignKey(blank=True, help_text='Mesa onde a comanda está sentada (opcional, apenas referência de entrega).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tabs', to='tables.table', verbose_name='mesa')),
            ],
            options={
                'verbose_name': 'comanda',
                'verbose_name_plural': 'comandas',
                'ordering': ['-created_at'],
            },
        ),
    ]
