# Generated by Django 5.2.7 on 2026-08-25 22:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nome ou número único da mesa (ex.: "Mesa 1").', max_length=100, unique=True, verbose_name='nome/número')),
                ('seats', models.PositiveIntegerField(help_text='Quantidade de lugares da mesa (no mínimo 1).', validators=[django.core.validators.MinValueValidator(1)], verbose_name='lugares')),
                ('status', models.CharField(choices=[('free', 'Livre'), ('occupied', 'Ocupada')], default='free', help_text='Indica se a mesa está livre ou ocupada.', max_length=10, verbose_name='status')),
                ('is_active', models.BooleanField(default=True, help_text='Mesas inativas permanecem no banco mas saem da visão de mesas.', verbose_name='ativa')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
            ],
            options={
                'verbose_name': 'mesa',
                'verbose_name_plural': 'mesas',
                'ordering': ['name'],
            },
        ),
    ]
