# Generated by Django 5.2.7 on 2026-08-25 22:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nome do item exibido no catálogo.', max_length=200, verbose_name='nome')),
                ('price', models.DecimalField(decimal_places=2, help_text='Preço unitário em reais (não pode ser negativo).', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='preço')),
                ('stock', models.IntegerField(default=0, help_text='Quantidade atual em estoque (não pode ser negativa).', validators=[django.core.validators.MinValueValidator(0)], verbose_name='estoque')),
                ('is_active', models.BooleanField(default=True, help_text='Itens inativos permanecem no banco mas saem do catálogo de vendas.', verbose_name='ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
            ],
            options={
                'verbose_name': 'item',
                'verbose_name_plural': 'itens',
                'ordering': ['name'],
            },
        ),
    ]
