# Generated by Django 5.2.7 on 2026-09-12 05:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_item_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='NoteSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(help_text='Texto curto da sugestão (ex.: "gelo", "rodela de limão").', max_length=100, verbose_name='sugestão')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('item', models.ForeignKey(help_text='Item ao qual a sugestão pertence.', on_delete=django.db.models.deletion.CASCADE, related_name='note_suggestions', to='inventory.item', verbose_name='item')),
            ],
            options={
                'verbose_name': 'sugestão de observação',
                'verbose_name_plural': 'sugestões de observação',
                'ordering': ['text'],
                'constraints': [models.UniqueConstraint(fields=('item', 'text'), name='unique_note_suggestion_per_item')],
            },
        ),
    ]
