# Generated by Django 5.2.7 on 2026-09-12 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_notesuggestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='requires_kitchen_preparation',
            field=models.BooleanField(default=True, help_text='Marque para itens preparados na cozinha. Bebidas e snacks de prateleira podem ser desligados para não seguir para a tela da cozinha.', verbose_name='requer preparo na cozinha'),
        ),
    ]
