# Generated by Django 5.2.7 on 2026-10-05 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_item_requires_kitchen_preparation'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='description',
            field=models.TextField(blank=True, help_text='Descrição opcional do item (ex.: ingredientes, acompanhamentos).', verbose_name='descrição'),
        ),
    ]
