# Generated by Django 5.2.7 on 2026-08-25 23:07

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        ('tables', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('open', 'Aberta'), ('done', 'Encerrada')], default='open', help_text='Pedidos novos começam em "aberta"; o fluxo de encerramento (#110) a move para "encerrada".', max_length=10, verbose_name='status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('table', models.ForeignKey(help_text='Mesa à qual o pedido está vinculado.', on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='tables.table', verbose_name='mesa')),
            ],
            options={
                'verbose_name': 'pedido',
                'verbose_name_plural': 'pedidos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(help_text='Quantidade vendida deste item no pedido (no mínimo 1).', validators=[django.core.validators.MinValueValidator(1)], verbose_name='quantidade')),
                ('unit_price', models.DecimalField(decimal_places=2, help_text='Preço unitário do item no momento do pedido (snapshot, não muda).', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='preço unitário')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_lines', to='inventory.item', verbose_name='item')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order', verbose_name='pedido')),
            ],
            options={
                'verbose_name': 'item do pedido',
                'verbose_name_plural': 'itens do pedido',
                'ordering': ['item__name'],
            },
        ),
    ]
