# Generated by Django 5.2.7 on 2026-09-12 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_orderitem_is_prepared'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='auto_print_failed',
            field=models.BooleanField(default=False, help_text='Marcado quando a impressão automática na criação do pedido (#237) não consegue alcançar a impressora. A cozinha vê um aviso vermelho persistente no card até que uma reimpressão (manual ou automática) tenha sucesso, momento em que o flag é limpo.', verbose_name='falha na impressão automática'),
        ),
    ]
